name: main-workflow

env: {}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu_latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.14"
      - name: Print Go version
        run: go version
      - name: Run unit tests
        run: go test -v ./...
